n=float(input("Enter percentage of marks : "))
if n>=95:print("S")
elif n>=85:print("A+")
elif n>=75:print("A")
elif n>=65:print("B+")
elif n>=55:print("B")
elif n>=45:print("C")
elif n>=35:print("D")
else:print("Failed")